# Generated by Django 2.2.24 on 2021-07-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
